#!/usr/bin/env python3
import argparse
import gzip
import json
from pathlib import Path

try:
    from shapely.geometry import shape, mapping
    from shapely.ops import unary_union
except Exception as exc:  # pragma: no cover
    raise SystemExit(
        "Missing dependency: shapely. Install with `python3 -m pip install shapely`.\n"
        f"Error: {exc}"
    )


def parse_args():
    parser = argparse.ArgumentParser(description="Extract campus boundary from cadastre parcels.")
    parser.add_argument("--parcelles", required=True, help="Path to cadastre parcels .json.gz")
    parser.add_argument("--section", required=True, help="Cadastral section (e.g., AT)")
    parser.add_argument("--numbers", required=True, help="Comma-separated parcel numbers (e.g., 54,56,58)")
    parser.add_argument("--campus", required=True, help="Campus name (e.g., Triolet)")
    parser.add_argument("--source", default="cadastre-etalab", help="Source label")
    parser.add_argument("--out-geojson", default="data/campus_triolet.geojson", help="Output GeoJSON")
    parser.add_argument("--out-sql", default="src/main/resources/campus_boundaries.sql", help="Output SQL file")
    return parser.parse_args()


def normalize_num(value):
    if value is None:
        return ""
    return str(value).strip().lstrip("0")


def main():
    args = parse_args()
    parcel_numbers = {normalize_num(v) for v in args.numbers.split(",") if v.strip()}
    section = args.section.strip().upper()

    parcels_path = Path(args.parcelles)
    if not parcels_path.exists():
        raise SystemExit(f"Parcelles file not found: {parcels_path}")

    with gzip.open(parcels_path, "rt", encoding="utf-8") as f:
        data = json.load(f)

    selected = []
    for feat in data.get("features", []):
        props = feat.get("properties", {})
        feat_section = str(props.get("section") or props.get("SECTION") or "").strip().upper()
        feat_num = normalize_num(props.get("numero") or props.get("NUMERO") or props.get("numero_parcelle"))
        if feat_section != section:
            continue
        if feat_num not in parcel_numbers:
            continue
        geom = feat.get("geometry")
        if geom:
            selected.append(shape(geom))

    if not selected:
        raise SystemExit("No parcels matched. Check section/parcel numbers.")

    boundary = unary_union(selected)

    feature = {
        "type": "Feature",
        "properties": {
            "campus": args.campus,
            "source": args.source,
            "section": section,
            "parcels": sorted(parcel_numbers),
        },
        "geometry": mapping(boundary),
    }
    feature_collection = {"type": "FeatureCollection", "features": [feature]}

    out_geojson = Path(args.out_geojson)
    out_geojson.parent.mkdir(parents=True, exist_ok=True)
    out_geojson.write_text(json.dumps(feature_collection, ensure_ascii=False), encoding="utf-8")

    out_sql = Path(args.out_sql)
    out_sql.parent.mkdir(parents=True, exist_ok=True)
    geojson_text = json.dumps(feature_collection, ensure_ascii=False).replace("'", "''")
    out_sql.write_text(
        "-- Campus boundaries import. Generated by scripts/cadastre_extract_triolet.py\n"
        f"INSERT INTO campus_boundary (campus, source, geojson) VALUES "
        f"('{args.campus}', '{args.source}', '{geojson_text}');\n",
        encoding="utf-8"
    )

    print(f"Wrote {out_geojson} and {out_sql}")


if __name__ == "__main__":
    main()
